### PR TITLE
feat: add stackblitz project titles

### PR DESCRIPTION
**Pull request by eidam**

### CODE REVIEW

**Review by lukeed — COMMENTED** [review]
Should we allow user to customize? Then the titles listed here are default values

**Comment by eidam** [comment]
> Should we allow user to customize? Then the titles listed here are default values

they can change it after its forked, its just what they see in stackblitz upon fork

**Comment by lukeed** [comment]
Ah gotcha, cool

Second thought: should we standardize the titles to highlight the template name?

```js
const title = `Create new "${subdir}" project`;
// or
const title = `Template: ${subdir}`
```

**Comment by eidam** [comment]
It will literally fork the project for them, and the title will be used as the name of the new (already forked) project. Having it prefixed with `template: ` could trick them to fork the forked one 😅 


Screenshot 2022-05-14 at 19 06 20

**Review by lukeed — APPROVED** [review]

**Pull request merged**
